name: build/link check

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v7

    - name: restore htmltest cache
      uses: actions/cache/restore@v6
      with:
        path: tmp/.htmltest
        # We want the latest cache to hit and be updated every time.
        key: htmltest-${{ github.run_id }}
        restore-keys: |
          htmltest

    - name: set up Hugo
      uses: peaceiris/actions-hugo@v3
      with:
        hugo-version: latest

    - name: build site
      run: make public

    - name: run htmltest
      uses: wjdp/htmltest-action@31be84a95c860a331e0cf9a99f71e3eb39d2f86b
      with:
        skip_external: true

    - name: save htmltest cache
      uses: actions/cache/save@v6
      if: always()
      with:
        path: tmp/.htmltest
        key: htmltest-${{ github.run_id }}

    # deploy to GitHub pages if this is the main branch
    - name: deploy
      uses: peaceiris/actions-gh-pages@v4
      if: github.ref == 'refs/heads/main'
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./public
